# -*- coding: utf-8 -*-
"""RAG ( MINI CHATBOT).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JcVV9wuGkWmSG9QS7-k-Kr2YAgN7tH41
"""

!pip install langchain faiss-cpu sentence-transformers huggingface-hub transformers langchain-community langchain-huggingface

# TO AVOID WARNINGS
from langchain_core._api.deprecation import LangChainDeprecationWarning
import warnings

warnings.filterwarnings("ignore", category=LangChainDeprecationWarning)

from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter

from google.colab import drive
drive.mount('/content/drive')

import os
print(os.listdir('/content/drive/MyDrive'))

from langchain_community.document_loaders import DirectoryLoader,TextLoader

# loading the notepad files from the directory
loader = DirectoryLoader('/content/drive/MyDrive/TAJMAHAL',
glob="*.txt", loader_cls=TextLoader)
docs = loader.load()

from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=600,
    chunk_overlap=300
)

chunks = text_splitter.split_documents(docs)

from langchain_community.vectorstores import FAISS # database

from langchain_huggingface import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
embeddings

db = FAISS.from_documents(chunks, embeddings)
docs = db.docstore._dict

for i, (doc_id, doc) in enumerate(docs.items()):
    print(f"Document {i+1}")
    print("ID:", doc_id)
    print("Content:")
    print(doc.page_content)
    print("-" * 60)

vector = embeddings.embed_query("WhO BUILT TAJMAHAL?")

vector

from transformers import pipeline
import torch

pipe = pipeline(
    "text-generation",
    model="Qwen/Qwen2.5-3B-Instruct", # Changed MODEL
    device=0 if torch.cuda.is_available() else -1,
    max_new_tokens=200,
    temperature=0.0,
    do_sample=False,
    return_full_text=False
)

from langchain_community.vectorstores import FAISS
from langchain_community.vectorstores.faiss import DistanceStrategy

db = FAISS.from_documents(
    chunks,
    embedding=embeddings,
    distance_strategy=DistanceStrategy.COSINE,
    normalize_L2=True,
)

retriever = db.as_retriever(
    search_type="similarity",
    search_kwargs={
        "k": 1
    }
)

from langchain_huggingface import HuggingFacePipeline
llm = HuggingFacePipeline(pipeline=pipe)

def self_rag_part(question: str):
    # Retrieve context
    context = "\n\n".join(
        doc.page_content for doc in retriever.invoke(question)  # IT PASSES THE QUESTION
    )

    # Generate answer
    answer_prompt = f"""
Answer the question using only the provided context.
If the answer is not in the context, say "I don't have enough information from the provided context."
Keep the answer within 2-3 lines.

Context:
{context}

Question:
{question}

Answer:
"""

    answer = llm.invoke(answer_prompt).strip()

    # Verify answer
    critique_prompt = f"""
Context:
{context}

Question:
{question}

Answer:
{answer}

Is the answer fully supported by the context?
Reply with ONLY YES or NO.
"""

    critique = llm.invoke(critique_prompt).strip().upper()

    # Revise if needed
    if critique == "NO":
        revise_prompt = f"""
Using only the context, rewrite the answer correctly.
Keep it within 2-3 lines.

Context:
{context}

Question:
{question}

Answer:
"""
        return llm.invoke(revise_prompt).strip()

    return answer

print("Taj Mahal RAG Chatbot")
print("Type 'exit' to quit.\n")

while True:
    question = input("Enter your question about the Taj Mahal: ")

    # Exit condition
    if question.lower() in ["exit", "quit", "bye"]:
        print("Thank you for using the Taj Mahal RAG Chatbot!")
        break

    # Get answer from your RAG
    answer = self_rag_part(question)

    # Display answer
    print("\nAnswer:")
    print(answer)
    print("-" * 60)



